In [25]:
import numpy as np

In [27]:
my_list = list(range(1000000))
my_arr = np.arange(1000000)

In [28]:
%timeit [x**2 for x in my_list]
%timeit my_arr**2

136 ms ± 19.4 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
4.95 ms ± 846 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [29]:
lst = [2,3,4,5]
a = np.array(lst)
print(a)

[2 3 4 5]


In [30]:
b = np.zeros(10)
print(b)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [32]:
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [33]:
np.ones([2,5], dtype = int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [40]:
np.arange(10,0,-2)

array([10,  8,  6,  4,  2])

In [45]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [50]:
np.eye(4,3,1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [53]:
np.random.randint(100)

73

In [55]:
from numpy import random as rd

In [66]:
rd.randint(100)

12

In [76]:
rd.rand()

0.3132735169322751

In [78]:
rd.randint(10,size=[5,5])

array([[3, 9, 8, 7, 3],
       [6, 5, 1, 9, 3],
       [4, 8, 1, 4, 0],
       [3, 9, 2, 0, 4],
       [9, 2, 7, 7, 9]], dtype=int32)

In [77]:
rd.randint(1,100,[5,5])

array([[85, 12, 29, 30, 15],
       [51, 69, 88, 88, 95],
       [97, 87, 14, 10,  8],
       [64, 62, 23, 58,  2],
       [ 1, 61, 82,  9, 89]], dtype=int32)

In [87]:
lst = 'orange blueberry canberry durian'.split()
rd.choice(lst,size=[10],p=[0.1,0.5,0.3,0.1])

array(['durian', 'blueberry', 'blueberry', 'blueberry', 'orange',
       'canberry', 'blueberry', 'blueberry', 'blueberry', 'orange'],
      dtype='<U9')

In [83]:
lst

['a', 'b', 'c', 'd']

In [88]:
rd.normal()

-1.1173103486352778

In [89]:
a = np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [94]:
a.reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [95]:
a = np.arange(1,5)
b = np.array([2,2,3,4])

In [96]:
a

array([1, 2, 3, 4])

In [97]:
b

array([2, 2, 3, 4])

In [98]:
a*b

array([ 2,  4,  9, 16])

In [102]:

a = np.arange(12).reshape(4,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [103]:
a[1,2]

np.int64(5)

In [104]:
a = np.arange(50).reshape(5,10)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [105]:
b = np.arange(5).reshape(5,1)
b

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [106]:
rd.seed(1)
aa = rd.randint(100,size = [5,6])
aa

array([[37, 12, 72,  9, 75,  5],
       [79, 64, 16,  1, 76, 71],
       [ 6, 25, 50, 20, 18, 84],
       [11, 28, 29, 14, 50, 68],
       [87, 87, 94, 96, 86, 13]], dtype=int32)

In [111]:
aa[[1,2],[3,4]]


array([ 1, 18], dtype=int32)

In [112]:
aa[1:3,:]

array([[79, 64, 16,  1, 76, 71],
       [ 6, 25, 50, 20, 18, 84]], dtype=int32)

In [114]:
aa[[0,3,3,2,0]]

array([[37, 12, 72,  9, 75,  5],
       [11, 28, 29, 14, 50, 68],
       [11, 28, 29, 14, 50, 68],
       [ 6, 25, 50, 20, 18, 84],
       [37, 12, 72,  9, 75,  5]], dtype=int32)

In [115]:
aa>50

array([[False, False,  True, False,  True, False],
       [ True,  True, False, False,  True,  True],
       [False, False, False, False, False,  True],
       [False, False, False, False, False,  True],
       [ True,  True,  True,  True,  True, False]])

In [116]:
aa[aa>50]

array([72, 75, 79, 64, 76, 71, 84, 68, 87, 87, 94, 96, 86], dtype=int32)